version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - two-tier-nt

    restart: always
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot","-proot"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 60s


  flask-app:
    container_name: two-tier-app
    # build:
    #   context: .
    image: $DOCKER_IMAGE_NAME

    ports:
      - "5000:5000"

    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

    networks:
      - two-tier-nt

    depends_on:
      - mysql
        # condition: service_healthy

    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 60s

volumes:
  mysql_data:

networks:
  two-tier-nt: